[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# SPA fallback (you also have public/_redirects which Vite will copy to dist)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
